apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeseries-api
  namespace: timeseries-api
  labels:
    app: timeseries-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeseries-api
  template:
    metadata:
      labels:
        app: timeseries-api
    spec:
      containers:
        - name: timeseries-api
          image: ghcr.io/needleinajaystack/go-timeseries-api@sha256:afb08ed58478ecf4fe9493a627ab002f92e95b33a543e7050e4a8ce35016e5dd
          ports:
            - containerPort: 80
            - name: metrics
              containerPort: 2112
          env:
            - name: HOST
              value: localhost
            - name: PORT
              value: '80'
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: timeseries-api
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timeseries-api
                  key: password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: timeseries-api
                  key: apiKey
            - name: DATABASE_HOST
              value: cluster
            - name: DATABASE_NAME
              value: timeseries_api
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cluster
                  key: superuser-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster
                  key: superuser-password
            - name: DATABASE_SSL
              value: prefer
            - name: MQTT_ADDRESS
              value: tcp://192.168.4.100:31883
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: timeseries-api
                  key: mqttUsername
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timeseries-api
                  key: mqttPassword
