apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timeseries-api
  namespace: timeseries-api
  labels:
    app: timeseries-api
spec:
  ingressClassName: haproxy
  rules:
    - host: data.herron.dev
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: timeseries-api
              port:
                number: 80
    - host: utility-api.herron.dev
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: timeseries-api
              port:
                number: 80
