apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: acme
    external-dns.alpha.kubernetes.io/target: "97.117.2.112"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    haproxy.org/ssl-redirect: "false"
  name: timeseries-api
  namespace: timeseries-api
  labels:
    app: timeseries-api
spec:
  ingressClassName: haproxy
  rules:
    - host: data.herron.dev
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: timeseries-api
              port:
                number: 80
    - host: utility-api.herron.dev
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: timeseries-api
              port:
                number: 80
  tls:
    - hosts:
      - data.herron.dev
      - utility-api.herron.dev
      secretName: timeseries-api-tls
