apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  namespace: timeseries-api
  name: postgres-config
spec:
  postgresVersion: '17'
  postgresql.conf:
    # See defaults: https://stackgres.io/doc/latest/reference/crd/sgpostgresconfig/#default-values
    shared_buffers: '512MB'
    shared_preload_libraries: pg_stat_statements,auto_explain,timescaledb
    random_page_cost: '1.5'
    password_encryption: 'scram-sha-256'
    log_min_duration_statement: '-1'
    log_checkpoints: off
    log_connections: off
    log_disconnections: off
    log_lock_waits: off
    log_temp_files: '-1'
    log_autovacuum_min_duration: '-1'
