apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: acme
    haproxy.org/ssl-redirect: "false"
  name: radicale
  namespace: radicale
  labels:
    app: radicale
spec:
  ingressClassName: haproxy
  rules:
    - host: radicale.herron.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radicale
                port:
                  name: radicale
    - host: cal.herron.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radicale
                port:
                  name: radicale
  tls:
    - hosts:
      - radicale.herron.dev
      - cal.herron.dev
      secretName: radicale-tls
