apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: openclaw
data:
  openclaw.json: |-
    {
      "agents": {
        "defaults": {
          "model": {
            "primary": "anthropic/claude-sonnet-4-20250514"
          }
        }
      },
      "channels": {
        "telegram": {
          "allowFrom": [
            "jay_herron"
          ],
          "dmPolicy": "allowlist",
          "enabled": true,
          "groups": {
            "*": {
              "requireMention": true
            }
          }
        }
      },
      "gateway": {
        "auth": {
          "mode": "token"
        },
        "bind": "lan"
      },
    }
